spring.application.name=GestionPacientes
spring.config.import=optional:file:.env[.properties]

server.port=8081
server.servlet.context-path=/gestionPacientes
spring.datasource.url=jdbc:postgresql://db.jgjxzkqrnyrcrtmfatcn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}

# Configuración de Cloudinary
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

# Mantiene los nombres exactos (respetando mayúsculas de tu SQL)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Evita que Spring borre tus tablas creadas a mano
spring.jpa.hibernate.ddl-auto=update
